//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.09 at 08:11:20 PM GMT 
//


/*
 * The below file was generated by xjc from a xml schema definition file adapted from 
 * the Externalisation Labs (weeks 3 & 4) @ https://learnonline.gmit.ie/course/view.php?id=590
 */

package ie.gmit.sw.DS_Project;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ie.gmit.sw.ds package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CarOrder_QNAME = new QName("http://sw.gmit.ie/ds/", "CarOrder");
    private final static QName _Comment_QNAME = new QName("http://sw.gmit.ie/ds/", "comment");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ie.gmit.sw.ds
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Cars }
     * 
     */
    public Cars createCars() {
        return new Cars();
    }

    /**
     * Create an instance of {@link CarOrder }
     * 
     */
    public CarOrder createCarOrder() {
        return new CarOrder();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link Cars.Car }
     * 
     */
    public Cars.Car createCarsCar() {
        return new Cars.Car();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CarOrder }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sw.gmit.ie/ds/", name = "CarOrder")
    public JAXBElement<CarOrder> createCarOrder(CarOrder value) {
        return new JAXBElement<CarOrder>(_CarOrder_QNAME, CarOrder.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sw.gmit.ie/ds/", name = "comment")
    public JAXBElement<String> createComment(String value) {
        return new JAXBElement<String>(_Comment_QNAME, String.class, null, value);
    }

}
